#Playbook designed to configure a web VM and setup DVWA
- name: Config Web VM with Docker
  hosts: webservers
  become: true
  tasks:
      #Uses the apt module to install docker.io
    - name: docker.io
      apt:
        force_apt_get: yes
        update_cache: yes
        name: docker.io
        state: present
        
      #Uses the apt module to install pip3
    - name: Install pip3
      apt:
        force_apt_get: yes
        name: python3-pip
        state: present

      #Uses the pip module to install the Docker Python module
    - name: Install Docker python module
      pip:
        name: docker
        state: present
        
      #Uses the docker container module to download and launch a Damn Vulnerable Web Application (DVWA) image  
    - name: download and launch docker web container
      docker_container:
        name: dvwa
        image: cyberxsecurity/dvwa
        state: started
        restart_policy: always
        published_ports: 80:80

      #Uses the systemd module to ensure that docker launches at start up
    - name: Enable docker service
      systemd:
        name: docker
        enabled: yes        
